spring:
  application:
    name: notification
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
  mail:
    host: smtp.yandex.com
    port: 465
    username: ${SMTP_ADDRESS}
    password: ${SMTP_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          debug: false  # TEST_ONLY
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    exchange:
        name: notifications.exchange
    queue:
        name: notifications.queue
    routing:
        key: notifications.routing.key
