spring:
  application:
    name: trip
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    exchange-notifications: notifications.exchange
    routing-key-notifications: notifications.routing.key
    exchange-reports: report.exchange
    routing-key-reports: report.routing.key
    exchange-kanban: kanban.exchange
    routing-key-kanban: kanban.routing.key

base-url: ${TRIP_SERVICE_BASE_URL}
